### ISSUE TITLE
WT901C

### ISSUE THREAD

**Issue by mat214** [W-Geronius/signalk-hwt901b-imu#7]
Hello, does the plugin work with the WT901C RS232 model? Thank you for your help !

**Comment by mpolazzo** [comment]
Hi, I tried it only with the hwt901b. I don’t know what is the difference between B and C.Il giorno 5 nov 2022, alle ore 16:20, mat214 ***@***.***> ha scritto:﻿
Hello, does the plugin work with the WT901C RS232 model? Thank you for your help !

**Comment by W-Geronius** [comment]
I have no feedback so far from users running the plugin on a WT901C. The difference between B and C is tilt compensation - I would not expect incompatibilities however 

Live results of 901B-232  weren't too impressive for me - so I am conducting more tests on the hardware before further improving this plugin

**Comment by ak68-hub** [comment]
Yes, WT901C-485 is working ....
